In [1]:
2+2

4

In [2]:
import numpy as np

In [3]:
my_array=np.array([11,12,13,14,15,16,17,18])
print(np.reshape(my_array,(2,4)))

[[11 12 13 14]
 [15 16 17 18]]


In [5]:
zero_array=np.zeros((4,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
one_array=np.ones((3,4))
print(one_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
count_array=np.arange(4,14)
print(count_array)

[ 4  5  6  7  8  9 10 11 12 13]


In [9]:
array=np.arange(0,6,1.5)
print(array)

[0.  1.5 3.  4.5]


In [11]:
array=np.full((2,2),4)
print(array)

[[4 4]
 [4 4]]


In [12]:
matrix=np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
matrix=np.diag((10,12))
print(matrix)

[[10  0]
 [ 0 12]]


In [16]:
array=np.random.uniform(0,10, size=(3,3))
print(array)


[[6.17454368 7.38564083 6.96323317]
 [6.28884236 5.90141372 8.09061559]
 [2.61053634 4.39725554 1.18737473]]


In [20]:
array=np.random.randint(10,20, size=(3,3))
print(array)

[[16 12 17]
 [14 11 19]
 [18 19 12]]


In [24]:
myArray=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(myArray[0,:2])
myArray[:2,:]=0
print(myArray)

[11 12]
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [26]:
array=np.arange(21)
print(array[::-1])

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [28]:
myArray=np.array([[11,12,13],[14,15,16]])
array=np.reshape(myArray,(3,2))
print(array)

[[11 12]
 [13 14]
 [15 16]]


In [32]:
myArray=np.arange(10)
print("Squared array:", np.square(myArray))
print("Square root:",np.sqrt(myArray))
print(np.square(myArray)*np.sqrt(myArray))

Squared array: [ 0  1  4  9 16 25 36 49 64 81]
Square root: [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [40]:
myArray=np.array([[11,12,13],[14,15,16],[17,18,19]])
myArray=np.vstack([myArray,[20,21,22]])
print(myArray)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [41]:
myArray=np.array([[11,12,13],[14,15,16],[17,18,19]])
column=np.array([[30],[40],[50]])
result_array = np.hstack([myArray,column])
print(result_array)

[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


In [48]:
myArray=np.zeros((2,2))
ones=np.ones((2,1))
myArray=np.hstack((myArray,ones))
print(myArray)

[[0. 0. 1.]
 [0. 0. 1.]]


In [49]:
myArray=np.zeros((2,2))
ones=np.ones((2,1))
myArray=np.hstack((myArray,ones))
twos=np.full((2,myArray.shape[1]),2)
myArray=np.vstack((myArray,twos))
print(myArray)

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [50]:
myArray=np.zeros((2,2))
ones=np.ones((2,1))
myArray=np.hstack((myArray,ones))
twos=np.full((2,myArray.shape[1]),2)
myArray=np.vstack((myArray,twos))
column=myArray[:,:-1]
print(column)

[[0. 0.]
 [0. 0.]
 [2. 2.]
 [2. 2.]]


In [54]:
myArray=np.zeros((2,2))
ones=np.ones((2,1))
myArray=np.hstack((myArray,ones))
twos=np.full((2,myArray.shape[1]),2)
myArray=np.vstack((myArray,twos))
result_array=myArray[:-1,:]
print(result_array)

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]]


In [59]:
myArray=np.matrix([[1,2,3],[4,5,6],[9,8,7]])
array=np.delete(myArray,1,axis=1)
print(array)

[[1 3]
 [4 6]
 [9 7]]


In [62]:
exercise_1=np.array([1,2,3,4,5,6,7,8,9])
exercise_1[exercise_1 % 2 !=0 ]=-1
exercise_1=np.insert(exercise_1,0,0)
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [64]:
exercise_2=np.array([0,1,2,3,4,5,6,7,8])
array=exercise_2.reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
exercise_3=np.arange(4).reshape(2,-1)
array=exercise_3+202
print(array)

[[202 203]
 [204 205]]


In [67]:
random=np.random.randint(30,41,size=10)
print(random)

[32 34 32 38 39 30 37 32 35 35]


In [68]:
x=np.array([21,64,86,22,74,55,81,71,90,89])
y=np.array([21,7,3,45,10,29,55,4,37,18])
y_greater=np.where(x>y)
equals_y=np.where(x==y)
print(y_greater,equals_y)

(array([1, 2, 4, 5, 6, 7, 8, 9]),) (array([0]),)


In [69]:
exercise_6=np.arange(100).reshape(5,-1)
first_four=exercise_6[:,:4]
print(first_four)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
